### ISSUE TITLE
Translate README to English

### ISSUE THREAD

**Issue by hassanabidpk** [DjangoGirlsSeoul/seminar#1]
@RachellCalhoun  please help proof read 📝 it after I translate it to english  😄

**Comment by RachellCalhoun** [comment]
Will do!

**Comment by hassanabidpk** [comment]
You can review here https://github.com/DjangoGirlsSeoul/seminar/blob/master/readme-en.md @RachellCalhoun

**Comment by sujinleeme** [comment]
@hassanabidpk As by Korean Ver. was updated, I revised English Ver.
